"""Built-in sample corpus for demo mode."""

SAMPLE_DOCS = [
    # Technology
    "Machine learning algorithms can automatically improve through experience and data.",
    "Neural networks are computing systems inspired by biological neural networks.",
    "Deep learning is a subset of machine learning using multi-layered neural networks.",
    "Natural language processing enables computers to understand human language.",
    "Computer vision allows machines to interpret and understand visual information.",
    "Reinforcement learning trains agents through reward and punishment signals.",
    "Transfer learning reuses a pre-trained model on a new related problem.",
    "Generative adversarial networks consist of two neural networks competing against each other.",
    "Recurrent neural networks are designed to recognize patterns in sequences of data.",
    "Convolutional neural networks are commonly used for image recognition tasks.",
    "Transformer architecture revolutionized natural language processing tasks.",
    "Attention mechanisms allow models to focus on relevant parts of the input.",
    "BERT is a pre-trained language model that understands context bidirectionally.",
    "GPT models generate text by predicting the next token in a sequence.",
    "Embedding vectors represent words or documents as dense numerical vectors.",
    "Vector databases enable efficient similarity search over embedding spaces.",
    "Cosine similarity measures the angle between two vectors in high-dimensional space.",
    "Approximate nearest neighbor search trades accuracy for speed in large datasets.",
    "Dimensionality reduction techniques compress high-dimensional data into fewer dimensions.",
    "Principal component analysis finds orthogonal axes of maximum variance.",
    # Science
    "Photosynthesis converts sunlight into chemical energy in plants.",
    "DNA carries the genetic instructions for all known living organisms.",
    "The theory of relativity describes the relationship between space and time.",
    "Quantum mechanics describes the behavior of matter at the atomic level.",
    "Evolution by natural selection explains the diversity of life on Earth.",
    "The periodic table organizes chemical elements by their atomic properties.",
    "Mitochondria are the powerhouses of the cell producing ATP.",
    "Plate tectonics explains the movement of Earth's lithospheric plates.",
    "The Big Bang theory describes the origin of the universe from a singularity.",
    "Black holes are regions of spacetime where gravity is extremely strong.",
    "Dark matter makes up approximately 27% of the universe's mass-energy.",
    "The human genome contains approximately 3 billion base pairs of DNA.",
    "Neurons communicate through electrical and chemical signals called synapses.",
    "Antibiotics fight bacterial infections but are ineffective against viruses.",
    "Climate change is driven by increasing greenhouse gas concentrations.",
    "The water cycle describes the continuous movement of water on Earth.",
    "Enzymes are biological catalysts that speed up chemical reactions.",
    "Stem cells can differentiate into many different types of specialized cells.",
    "The speed of light in a vacuum is approximately 299,792 kilometers per second.",
    "Gravity is the force of attraction between objects with mass.",
    # History & Society
    "The Industrial Revolution transformed manufacturing processes in the 18th century.",
    "Democracy originated in ancient Athens as a system of direct citizen participation.",
    "The printing press invented by Gutenberg revolutionized information dissemination.",
    "The Renaissance was a cultural movement that began in Italy in the 14th century.",
    "World War II was the deadliest conflict in human history.",
    "The United Nations was established in 1945 to promote international cooperation.",
    "The internet was originally developed as a military communication network.",
    "Globalization has interconnected economies and cultures worldwide.",
    "The French Revolution established principles of citizenship and inalienable rights.",
    "The Agricultural Revolution marked the transition from hunting to farming.",
    # Business & Economics
    "Supply and demand determine the market price of goods and services.",
    "Inflation refers to the general increase in prices over time.",
    "Gross domestic product measures the total economic output of a country.",
    "Compound interest allows investments to grow exponentially over time.",
    "Diversification reduces investment risk by spreading across different assets.",
    "The stock market enables companies to raise capital through public trading.",
    "Central banks control monetary policy to maintain economic stability.",
    "International trade allows countries to specialize in their comparative advantages.",
    "Entrepreneurship involves creating new businesses to solve market problems.",
    "Blockchain technology enables decentralized and transparent transaction records.",
    # Health & Medicine
    "Vaccines stimulate the immune system to develop protection against diseases.",
    "Regular exercise improves cardiovascular health and mental wellbeing.",
    "A balanced diet provides essential nutrients for optimal body function.",
    "Sleep is essential for memory consolidation and physical recovery.",
    "Meditation has been shown to reduce stress and improve mental clarity.",
    "Antibodies are proteins produced by the immune system to fight pathogens.",
    "Chronic stress can lead to inflammation and various health problems.",
    "Telemedicine enables remote healthcare delivery through digital technology.",
    "Genetic testing can identify predisposition to certain hereditary conditions.",
    "Physical therapy helps restore movement and function after injury.",
    # Arts & Culture
    "Music activates multiple areas of the brain simultaneously.",
    "Abstract art emphasizes form, color, and line over realistic representation.",
    "Literature provides insights into the human condition across cultures.",
    "Photography captures moments in time through the interaction of light and optics.",
    "Architecture combines engineering principles with artistic design.",
    "Film combines visual storytelling with sound to create immersive narratives.",
    "Poetry uses rhythm and imagery to convey emotion and meaning.",
    "Dance is a universal form of expression found in every human culture.",
    "Sculpture transforms raw materials into three-dimensional artistic forms.",
    "Theater combines performance, dialogue, and staging to tell stories live.",
    # Environment
    "Renewable energy sources include solar, wind, and hydroelectric power.",
    "Deforestation contributes to habitat loss and increased carbon emissions.",
    "Ocean acidification threatens marine ecosystems and coral reefs.",
    "Biodiversity is essential for ecosystem resilience and stability.",
    "Sustainable agriculture aims to meet food needs without depleting resources.",
    "Recycling reduces waste and conserves natural resources and energy.",
    "Electric vehicles produce zero direct emissions during operation.",
    "Urban planning influences transportation patterns and energy consumption.",
    "Conservation efforts protect endangered species from extinction.",
    "Carbon capture technology removes CO2 from the atmosphere.",
    # Technology Applications
    "Cloud computing provides on-demand access to shared computing resources.",
    "Cybersecurity protects systems and networks from digital attacks.",
    "The Internet of Things connects everyday devices to the internet.",
    "Augmented reality overlays digital information onto the physical world.",
    "Autonomous vehicles use sensors and AI to navigate without human input.",
    "5G networks provide faster data speeds and lower latency than previous generations.",
    "Edge computing processes data closer to where it is generated.",
    "Digital twins create virtual replicas of physical systems for simulation.",
    "Quantum computing uses quantum bits to solve problems beyond classical computers.",
    "Robotic process automation streamlines repetitive business tasks.",
    # Additional for 100+ count
    "API design principles include consistency, simplicity, and clear documentation.",
    "Microservices architecture decomposes applications into small independent services.",
    "Continuous integration automatically tests code changes before merging.",
    "Version control systems track and manage changes to source code.",
    "Containerization packages applications with their dependencies for consistent deployment.",
    "Load balancing distributes network traffic across multiple servers.",
    "Caching improves performance by storing frequently accessed data in fast storage.",
    "Database indexing speeds up data retrieval operations significantly.",
    "Message queues enable asynchronous communication between system components.",
    "GraphQL provides a flexible query language for APIs.",
]

# Select ~20% as queries for recall@k testing
SAMPLE_QUERY_INDICES = list(range(0, len(SAMPLE_DOCS), 5))  # Every 5th document
