"""Generate JSON and Markdown gap reports."""

import json

from models import GapReport


def to_json(reports: list[GapReport]) -> str:
    """Generate a JSON coverage report."""
    total = len(reports)
    monitored = sum(1 for r in reports if r.is_monitored)
    avg_coverage = (
        sum(r.coverage_pct for r in reports) / total if total else 0
    )

    data = {
        "summary": {
            "total_services": total,
            "monitored_services": monitored,
            "unmonitored_services": total - monitored,
            "average_coverage_pct": round(avg_coverage, 1),
        },
        "services": [
            {
                "name": r.service_name,
                "type": r.service_type.value,
                "is_monitored": r.is_monitored,
                "coverage_pct": r.coverage_pct,
                "existing_alerts": r.existing_alerts,
                "required_metrics": r.required_metrics,
                "missing_metrics": r.missing_metrics,
            }
            for r in reports
        ],
    }
    return json.dumps(data, indent=2, ensure_ascii=False)


def to_markdown(reports: list[GapReport]) -> str:
    """Generate a Markdown coverage report."""
    total = len(reports)
    monitored = sum(1 for r in reports if r.is_monitored)
    avg_coverage = (
        sum(r.coverage_pct for r in reports) / total if total else 0
    )

    lines = [
        "# Oncall Monitoring Gap Report",
        "",
        "## Summary",
        "",
        f"| Metric | Value |",
        f"|--------|-------|",
        f"| Total services | {total} |",
        f"| Monitored | {monitored} |",
        f"| Unmonitored | {total - monitored} |",
        f"| Avg coverage | {avg_coverage:.1f}% |",
        "",
        "## Service Coverage",
        "",
        "| Service | Type | Monitored | Coverage | Alerts | Gaps |",
        "|---------|------|-----------|----------|--------|------|",
    ]

    for r in reports:
        mon = "✅" if r.is_monitored else "❌"
        alerts = ", ".join(r.existing_alerts) if r.existing_alerts else "—"
        gaps = ", ".join(r.missing_metrics) if r.missing_metrics else "—"
        cov_bar = _coverage_bar(r.coverage_pct)
        lines.append(
            f"| {r.service_name} | {r.service_type.value} "
            f"| {mon} | {cov_bar} {r.coverage_pct}% "
            f"| {alerts} | {gaps} |"
        )

    # Detail sections for services with gaps
    gap_services = [r for r in reports if r.missing_metrics]
    if gap_services:
        lines.extend(["", "## Gap Details", ""])
        for r in gap_services:
            lines.append(f"### {r.service_name} ({r.service_type.value})")
            lines.append("")
            if not r.is_monitored:
                lines.append(
                    "> ⚠️ **Not scraped by Prometheus** — "
                    "no metrics are being collected"
                )
                lines.append("")
            lines.append(f"**Coverage: {r.coverage_pct}%**")
            lines.append("")
            if r.existing_alerts:
                lines.append("Existing alerts:")
                for a in r.existing_alerts:
                    lines.append(f"- ✅ {a}")
                lines.append("")
            lines.append("Missing metric coverage:")
            for m in r.missing_metrics:
                lines.append(f"- ❌ {m}")
            lines.append("")

    lines.extend(["---", f"*Generated by oncall-gap-predetector*", ""])
    return "\n".join(lines)


def _coverage_bar(pct: float) -> str:
    """Generate a simple text coverage bar."""
    filled = int(pct / 10)
    empty = 10 - filled
    return f"[{'█' * filled}{'░' * empty}]"
