"""Remediation code generator for failed checklist items.

Generates:
- Health check endpoint file
- Basic test file
- Docker healthcheck configuration
"""

from __future__ import annotations

import os
from pathlib import Path

from .checklist import AuditReport
from .scanner import ScanResult


def generate_remediation(report: AuditReport, project_dir: str, output_dir: str | None = None) -> list[str]:
    """Generate remediation files for failed checklist items.

    Returns list of generated file paths (relative to output_dir).
    """
    out = Path(output_dir or os.path.join(project_dir, "generated"))
    out.mkdir(parents=True, exist_ok=True)

    generated = []
    scan = report.scan
    failed_ids = {item.id for item in report.failed_items}

    if "has_healthcheck" in failed_ids:
        path = _generate_healthcheck(out, scan)
        generated.append(str(path))

    if "has_tests" in failed_ids:
        path = _generate_tests(out, scan)
        generated.append(str(path))

    if "has_dockerfile" in failed_ids:
        path = _generate_dockerfile(out, scan)
        generated.append(str(path))

    if "has_error_handling" in failed_ids:
        path = _generate_error_handlers(out, scan)
        generated.append(str(path))

    if "has_env_management" in failed_ids:
        path = _generate_env_config(out, scan)
        generated.append(str(path))

    return generated


def _generate_healthcheck(out: Path, scan: ScanResult) -> Path:
    app_var = scan.app_variable or "app"
    code = f'''"""Health check endpoint — generated by vibe-audit."""
from fastapi import APIRouter

router = APIRouter(tags=["health"])


@router.get("/health")
async def health_check():
    """Basic health check endpoint for monitoring and load balancers."""
    return {{"status": "healthy", "service": "api"}}


@router.get("/health/ready")
async def readiness_check():
    """Readiness probe — checks if the service is ready to handle requests."""
    # TODO: Add dependency checks (database, cache, etc.)
    return {{"status": "ready"}}


# Usage: In your main app file, add:
#   from health import router as health_router
#   {app_var}.include_router(health_router)
'''
    path = out / "health.py"
    path.write_text(code)
    return path


def _resolve_path(path: str) -> str:
    """Replace path parameters like {user_id} with sample values."""
    import re
    def _replace(m):
        name = m.group(1)
        if "id" in name.lower():
            return "1"
        return "test"
    return re.sub(r"\{(\w+)\}", _replace, path)


def _generate_tests(out: Path, scan: ScanResult) -> Path:
    routes = scan.routes[:5]  # Take up to 5 routes for test generation

    test_cases = []
    for route in routes:
        method = route.method.lower()
        test_name = f"test_{route.function_name or route.path.strip('/').replace('/', '_')}_{method}"
        resolved = _resolve_path(route.path)
        test_cases.append(f'''
def {test_name}(client):
    """Test {method.upper()} {route.path}"""
    response = client.{method}("{resolved}")
    assert response.status_code in (200, 201, 204, 307, 422), \\
        f"Unexpected status {{response.status_code}} for {method.upper()} {route.path}"
''')

    if not test_cases:
        test_cases.append('''
def test_root(client):
    """Test root endpoint."""
    response = client.get("/")
    assert response.status_code in (200, 307, 404)
''')

    app_import = scan.app_variable or "app"
    # Try to guess the import path
    main_file = None
    for f in scan.python_files:
        if "main" in f:
            main_file = f
            break
    if main_file is None and scan.python_files:
        main_file = scan.python_files[0]

    import_module = "main"
    if main_file:
        import_module = main_file.replace("/", ".").replace(".py", "")

    code = f'''"""Basic API tests — generated by vibe-audit.

Run with: pytest {out.name}/test_api.py
"""
import pytest
from fastapi.testclient import TestClient

# Adjust the import below to match your project structure
from {import_module} import {app_import}


@pytest.fixture
def client():
    """Create a test client for the FastAPI app."""
    return TestClient({app_import})

{"".join(test_cases)}
'''
    path = out / "test_api.py"
    path.write_text(code)
    return path


def _generate_dockerfile(out: Path, scan: ScanResult) -> Path:
    code = '''# Dockerfile — generated by vibe-audit
FROM python:3.12-slim

WORKDIR /app

# Install dependencies
COPY requirements.txt* pyproject.toml* ./
RUN pip install --no-cache-dir -r requirements.txt 2>/dev/null || pip install --no-cache-dir . 2>/dev/null || true

COPY . .

EXPOSE 8000

# Health check for container orchestrators
HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 \\
    CMD python -c "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')" || exit 1

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
'''
    path = out / "Dockerfile"
    path.write_text(code)
    return path


def _generate_error_handlers(out: Path, scan: ScanResult) -> Path:
    app_var = scan.app_variable or "app"
    code = f'''"""Global error handlers — generated by vibe-audit."""
from fastapi import FastAPI, Request
from fastapi.responses import JSONResponse


def register_error_handlers({app_var}: FastAPI) -> None:
    """Register global exception handlers on the FastAPI app.

    Usage: In your main app file, add:
        from error_handlers import register_error_handlers
        register_error_handlers({app_var})
    """

    @{app_var}.exception_handler(Exception)
    async def unhandled_exception_handler(request: Request, exc: Exception):
        return JSONResponse(
            status_code=500,
            content={{
                "detail": "Internal server error",
                "type": type(exc).__name__,
            }},
        )

    @{app_var}.exception_handler(404)
    async def not_found_handler(request: Request, exc):
        return JSONResponse(
            status_code=404,
            content={{"detail": "Not found", "path": str(request.url)}},
        )
'''
    path = out / "error_handlers.py"
    path.write_text(code)
    return path


def _generate_env_config(out: Path, scan: ScanResult) -> Path:
    code = '''"""Environment configuration — generated by vibe-audit.

Uses Pydantic BaseSettings for type-safe environment variable management.
Create a .env file in your project root with the variables below.
"""
import os
from functools import lru_cache


class Settings:
    """Application settings loaded from environment variables.

    For production use, consider using pydantic-settings:
        from pydantic_settings import BaseSettings
    """

    def __init__(self):
        self.app_name: str = os.getenv("APP_NAME", "api")
        self.debug: bool = os.getenv("DEBUG", "false").lower() == "true"
        self.host: str = os.getenv("HOST", "0.0.0.0")
        self.port: int = int(os.getenv("PORT", "8000"))
        self.database_url: str = os.getenv("DATABASE_URL", "sqlite:///./app.db")
        self.secret_key: str = os.getenv("SECRET_KEY", "change-me-in-production")


@lru_cache
def get_settings() -> Settings:
    return Settings()


# Usage:
#   from config import get_settings
#   settings = get_settings()
#   print(settings.app_name)
'''
    path = out / "config.py"
    path.write_text(code)
    return path
