"""Export lessons from DB to various agent rule file formats."""
import json
from datetime import datetime


def export_claude_md(lessons: list[dict]) -> str:
    """Export lessons as CLAUDE.md format."""
    lines = [
        "# CLAUDE.md — Auto-generated Rules",
        "",
        f"> Generated by agent-knowledge-loop on {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        f"> Total lessons: {len(lessons)}",
        "",
    ]

    by_category = _group_by_category(lessons)
    for cat, cat_lessons in by_category.items():
        lines.append(f"## {cat.title()}")
        lines.append("")
        for lesson in cat_lessons:
            merge_info = f" (seen {lesson['merge_count']}x)" if lesson.get("merge_count", 1) > 1 else ""
            lines.append(f"- {lesson['rule']}{merge_info}")
        lines.append("")

    return "\n".join(lines)


def export_agents_md(lessons: list[dict]) -> str:
    """Export lessons as AGENTS.md format (Codex-style)."""
    lines = [
        "# AGENTS.md — Agent Guidelines",
        "",
        f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        "",
        "## Learned Rules",
        "",
        "The following rules were automatically extracted from past agent sessions.",
        "",
    ]

    by_category = _group_by_category(lessons)
    for cat, cat_lessons in by_category.items():
        lines.append(f"### {cat.title()}")
        lines.append("")
        for i, lesson in enumerate(cat_lessons, 1):
            lines.append(f"{i}. **Failure**: {lesson['failure']}")
            lines.append(f"   **Resolution**: {lesson['resolution']}")
            lines.append(f"   **Rule**: {lesson['rule']}")
            lines.append("")

    return "\n".join(lines)


def export_cursor_rules(lessons: list[dict]) -> str:
    """Export lessons as .cursor/rules format (MDC)."""
    lines = [
        "---",
        "description: Auto-generated rules from agent session analysis",
        f"globs: ['**/*']",
        "alwaysApply: true",
        "---",
        "",
        "# Learned Rules from Past Sessions",
        "",
    ]

    by_category = _group_by_category(lessons)
    for cat, cat_lessons in by_category.items():
        lines.append(f"## {cat.title()}")
        lines.append("")
        for lesson in cat_lessons:
            lines.append(f"- {lesson['rule']}")
        lines.append("")

    return "\n".join(lines)


EXPORTERS = {
    "claude.md": export_claude_md,
    "agents.md": export_agents_md,
    "cursor": export_cursor_rules,
}


def _group_by_category(lessons: list[dict]) -> dict[str, list[dict]]:
    groups = {}
    for lesson in lessons:
        cat = lesson.get("category", "general")
        groups.setdefault(cat, []).append(lesson)
    return groups
