import Handlebars from 'handlebars';

Handlebars.registerHelper('if_has', function(arr, options) {
  return (arr && arr.length) ? options.fn(this) : options.inverse(this);
});

const BASE_STYLES = `
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; line-height: 1.6; }
  .container { max-width: 800px; margin: 0 auto; padding: 2rem; }
  .hero { text-align: center; padding: 4rem 2rem; }
  .hero h1 { font-size: 2.5rem; margin-bottom: 1rem; }
  .hero .description { font-size: 1.2rem; opacity: 0.85; max-width: 600px; margin: 0 auto; }
  .section { padding: 3rem 2rem; }
  .section h2 { font-size: 1.8rem; margin-bottom: 1.5rem; }
  .features-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(250px, 1fr)); gap: 1.5rem; }
  .feature-card { padding: 1.5rem; border-radius: 8px; }
  .install-section pre { padding: 1rem; border-radius: 8px; overflow-x: auto; font-size: 0.9rem; }
  .install-section code { font-family: 'SF Mono', 'Fira Code', monospace; }
  .cta-section { text-align: center; padding: 3rem 2rem; }
  .footer { text-align: center; padding: 2rem; font-size: 0.85rem; opacity: 0.6; }
  a { text-decoration: none; }
  ul, ol { padding-left: 1.5rem; }
  li { margin-bottom: 0.5rem; }
  table { border-collapse: collapse; width: 100%; margin: 1rem 0; }
  th, td { border: 1px solid; padding: 0.5rem 0.75rem; text-align: left; }
  img { max-width: 100%; }
  .badge { display: inline-block; margin: 0.25rem; }
  .meta { font-size: 0.9rem; opacity: 0.7; margin-top: 0.5rem; }
`;

const THEME_STYLES = {
  minimal: `
    body { background: #fff; color: #333; }
    a { color: #0066cc; }
    .hero { border-bottom: 1px solid #eee; }
    .feature-card { background: #f8f9fa; border: 1px solid #e9ecef; }
    .install-section pre { background: #f5f5f5; border: 1px solid #e0e0e0; color: #333; }
    th, td { border-color: #ddd; }
    th { background: #f5f5f5; }
  `,
  dark: `
    body { background: #0d1117; color: #c9d1d9; }
    a { color: #58a6ff; }
    .hero { border-bottom: 1px solid #21262d; }
    .hero h1 { color: #f0f6fc; }
    .feature-card { background: #161b22; border: 1px solid #30363d; }
    .install-section pre { background: #161b22; border: 1px solid #30363d; color: #c9d1d9; }
    th, td { border-color: #30363d; }
    th { background: #161b22; }
    .section h2 { color: #f0f6fc; }
  `,
  gradient: `
    body { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: #fff; min-height: 100vh; }
    a { color: #ffd700; }
    .hero h1 { color: #fff; text-shadow: 0 2px 10px rgba(0,0,0,0.2); }
    .feature-card { background: rgba(255,255,255,0.12); border: 1px solid rgba(255,255,255,0.2); backdrop-filter: blur(10px); }
    .install-section pre { background: rgba(0,0,0,0.3); border: 1px solid rgba(255,255,255,0.15); color: #e0e0e0; }
    th, td { border-color: rgba(255,255,255,0.2); }
    th { background: rgba(255,255,255,0.1); }
    .section h2 { color: #fff; }
    .footer { color: rgba(255,255,255,0.5); }
  `,
};

const LANDING_TEMPLATE = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{{meta.name}}{{#if hero.title}} — {{hero.title}}{{/if}}</title>
  <style>${BASE_STYLES}{{themeStyles}}</style>
</head>
<body>
  <div class="container">
    <section class="hero">
      <h1>{{#if hero.title}}{{hero.title}}{{else}}{{meta.name}}{{/if}}</h1>
      {{#if meta.description}}<p class="description">{{meta.description}}</p>{{/if}}
      {{#if heroBadges}}<div class="badges">{{{heroBadges}}}</div>{{/if}}
      {{#if meta.version}}<p class="meta">v{{meta.version}}{{#if meta.license}} · {{meta.license}}{{/if}}{{#if meta.author}} · by {{meta.author}}{{/if}}</p>{{/if}}
    </section>

    {{#if_has features}}
    <section class="section features-section">
      {{#each features}}
      <h2>{{this.heading}}</h2>
      {{#if this.items.length}}
      <div class="features-grid">
        {{#each this.items}}
        <div class="feature-card">{{{this}}}</div>
        {{/each}}
      </div>
      {{else}}
      {{{this.content}}}
      {{/if}}
      {{/each}}
    </section>
    {{/if_has}}

    {{#if_has install}}
    <section class="section install-section">
      {{#each install}}
      <h2>{{this.heading}}</h2>
      {{{this.content}}}
      {{/each}}
    </section>
    {{/if_has}}

    {{#each other}}
    <section class="section">
      <h2>{{this.heading}}</h2>
      {{{this.content}}}
    </section>
    {{/each}}

    {{#if_has cta}}
    <section class="section cta-section">
      {{#each cta}}
      <h2>{{this.heading}}</h2>
      {{{this.content}}}
      {{/each}}
    </section>
    {{/if_has}}

    <footer class="footer">
      Generated by indie-launch-kit · {{meta.name}}
    </footer>
  </div>
</body>
</html>`;

const CHANGELOG_TEMPLATE = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Changelog — {{meta.name}}</title>
  <style>${BASE_STYLES}{{themeStyles}}
    .hash { font-family: monospace; font-size: 0.85em; opacity: 0.6; }
  </style>
</head>
<body>
  <div class="container">
    {{{changelogHtml}}}
    <footer class="footer">
      Generated by indie-launch-kit · {{meta.name}}
    </footer>
  </div>
</body>
</html>`;

export function renderLanding(data, theme = 'minimal') {
  const themeStyles = THEME_STYLES[theme] || THEME_STYLES.minimal;
  const template = Handlebars.compile(LANDING_TEMPLATE);
  return template({ ...data, themeStyles });
}

export function renderChangelog(meta, changelogHtml, theme = 'minimal') {
  const themeStyles = THEME_STYLES[theme] || THEME_STYLES.minimal;
  const template = Handlebars.compile(CHANGELOG_TEMPLATE);
  return template({ meta, changelogHtml, themeStyles });
}

export const AVAILABLE_THEMES = Object.keys(THEME_STYLES);
