"""CLAUDE.md compatible markdown generator.

Generates a CLAUDE.md file from parsed diagram data and mapping config,
providing architectural context that AI coding agents can consume.
"""

from .mermaid_parser import ParsedDiagram
from .mapper import ContextMapper, MappingConfig


def generate_claude_md(
    diagram: ParsedDiagram,
    config: MappingConfig,
    project_name: str = "Project",
) -> str:
    """Generate CLAUDE.md content from diagram and mapping config."""
    mapper = ContextMapper(config, diagram)
    contexts = mapper.get_all_contexts()

    lines = [
        f"# {project_name} — Architecture Context",
        "",
        "> Auto-generated by ai-code-context-bridge. Do not edit manually.",
        "",
        "## Architecture Overview",
        "",
    ]

    # Services table
    if diagram.nodes:
        lines.append("### Services & Components")
        lines.append("")
        lines.append("| ID | Name | Type | Layer | Technology |")
        lines.append("|---|---|---|---|---|")
        for node in diagram.nodes:
            lines.append(
                f"| `{node.id}` | {node.label} | {node.type} "
                f"| {node.layer} | {node.technology or '-'} |"
            )
        lines.append("")

    # Communication relationships
    if diagram.relationships:
        lines.append("### Communication Flows")
        lines.append("")
        for rel in diagram.relationships:
            src = rel.source
            tgt = rel.target
            label = f" ({rel.label})" if rel.label else ""
            tech = f" [{rel.technology}]" if rel.technology else ""
            lines.append(f"- `{src}` → `{tgt}`{label}{tech}")
        lines.append("")

    # File mapping rules
    if contexts:
        lines.append("## File-to-Service Mapping")
        lines.append("")
        lines.append(
            "When working on a file, check which service/layer it belongs to:"
        )
        lines.append("")
        for ctx in contexts:
            lines.append(f"### `{ctx.file_path}` → **{ctx.service}** ({ctx.layer})")
            if ctx.description:
                lines.append(f"  {ctx.description}")
            if ctx.related_services:
                related = ", ".join(f"`{s}`" for s in ctx.related_services)
                lines.append(f"  Communicates with: {related}")
            lines.append("")

    # Guidelines for AI agents
    lines.extend([
        "## Guidelines for AI Agents",
        "",
        "1. **Before modifying a file**, check which service it belongs to above",
        "2. **Respect layer boundaries**: don't import from a different layer "
        "without going through the proper interface",
        "3. **Check communication flows**: if your change affects an API "
        "consumed by another service, consider the downstream impact",
        "4. **New files** should follow the directory patterns listed above",
        "",
    ])

    return "\n".join(lines)
